# **BIG SALES PREDICTION USING RANDOM FOREST CLASSIFIER**



## **Objective**

The aim of a big sales prediction using a Random Forest Regressor is to accurately forecast future sales volumes for a business or product.

## **Data Source**

https://github.com/YBIFoundation/Dataset/blob/main/Big%20Sales%20Data.csv

## **Import Library**

In [ ]:
import pandas as pd
import numpy as np
!pip install -U ydata-profiling
!pip install pydantic-settings
!pip install --upgrade ydata-profiling
from ydata_profiling import ProfileReport


  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 356.2/356.2 kB 16.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 25.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.1/686.1 kB 42.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 103.6 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=d0a8cbefc3efae9cf443cb9dd17f913fb3cb30f8597f006e399168c5ac26f3b9
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin


In [ ]:
import pandas as pd
import numpy as np

## **Import Data**

In [ ]:
url = 'https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Big%20Sales%20Data.csv'
df=pd.read_csv(url)

## **Describe Data**

In [ ]:
df.describe()

Item_Weight  Item_Visibility      Item_MRP  Outlet_Establishment_Year  \
count  11815.000000     14204.000000  14204.000000               14204.000000   
mean      12.788355         0.065953    141.004977                1997.830681   
std        4.654126         0.051459     62.086938                   8.371664   
min        4.555000         0.000000     31.290000                1985.000000   
25%        8.710000         0.027036     94.012000                1987.000000   
50%       12.500000         0.054021    142.247000                1999.000000   
75%       16.750000         0.094037    185.855600                2004.000000   
max       30.000000         0.328391    266.888400                2009.000000   

       Item_Outlet_Sales  
count       14204.000000  
mean         2185.836320  
std          1827.479550  
min            33.290000  
25%           922.135101  
50%          1768.287680  
75%          2988.110400  
max         31224.726950

## **Data Visualization**

In [ ]:
df.head(5)

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDT36         12.3          Low Fat         0.111448   
1           FDT36         12.3          Low Fat         0.111904   
2           FDT36         12.3               LF         0.111728   
3           FDT36         12.3          Low Fat         0.000000   
4           FDP12          9.8          Regular         0.045523   

      Item_Type  Item_MRP Outlet_Identifier  Outlet_Establishment_Year  \
0  Baking Goods   33.4874            OUT049                       1999   
1  Baking Goods   33.9874            OUT017                       2007   
2  Baking Goods   33.9874            OUT018                       2009   
3  Baking Goods   34.3874            OUT019                       1985   
4  Baking Goods   35.0874            OUT017                       2007   

  Outlet_Size Outlet_Location_Type        Outlet_Type  Item_Outlet_Sales  
0      Medium               Tier 1  Supermarket Type1         436.608721  
1      Medium               Tier 2  Supermarket Type1         443.127721  
2      Medium               Tier 3  Supermarket Type2         564.598400  
3       Small               Tier 1      Grocery Store        1719.370000  
4      Medium               Tier 2  Supermarket Type1         352.874000

In [ ]:




# Generate a profile report
profile = ProfileReport(df, title="Pandas Profiling Report", explorative=True)
profile.to_notebook_iframe()




Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                11815 non-null  float64
 2   Item_Fat_Content           14204 non-null  object 
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object 
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object 
 7   Outlet_Establishment_Year  14204 non-null  int64  
 8   Outlet_Size                14204 non-null  object 
 9   Outlet_Location_Type       14204 non-null  object 
 10  Outlet_Type                14204 non-null  object 
 11  Item_Outlet_Sales          14204 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.3+ MB


## **Data Preprocessing**

In [ ]:
print(df.isnull().sum())

Item_Identifier                 0
Item_Weight                  2389
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                     0
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64


In [ ]:
df['Item_Weight'].fillna(df.groupby(['Item_Type'])['Item_Weight'].transform('mean'), inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                14204 non-null  float64
 2   Item_Fat_Content           14204 non-null  object 
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object 
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object 
 7   Outlet_Establishment_Year  14204 non-null  int64  
 8   Outlet_Size                14204 non-null  object 
 9   Outlet_Location_Type       14204 non-null  object 
 10  Outlet_Type                14204 non-null  object 
 11  Item_Outlet_Sales          14204 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.3+ MB


In [ ]:
df[['Item_Identifier']].value_counts()

Item_Identifier
NCZ54              10
NCZ42              10
DRA24              10
DRA59              10
NCZ30              10
                   ..
FDM52               7
FDL50               7
FDM10               7
FDI46               7
NCW54               7
Name: count, Length: 1559, dtype: int64

In [ ]:
df[['Item_Fat_Content']].value_counts()

Item_Fat_Content
Low Fat             8485
Regular             4824
LF                   522
reg                  195
low fat              178
Name: count, dtype: int64

In [ ]:
df.replace({'LF':'Low Fat','reg':'Regular','low fat':'Low Fat'},inplace=True)

In [ ]:
df[['Item_Fat_Content']].value_counts()

Item_Fat_Content
Low Fat             9185
Regular             5019
Name: count, dtype: int64

In [ ]:
df.replace({'Item_Fat_Content':{'Low Fat':0,'Regular':1}},inplace=True)

In [ ]:
df[['Item_Fat_Content']].value_counts()

Item_Fat_Content
0                   9185
1                   5019
Name: count, dtype: int64

In [ ]:
df[['Item_Type']].value_counts()

Item_Type            
Fruits and Vegetables    2013
Snack Foods              1989
Household                1548
Frozen Foods             1426
Dairy                    1136
Baking Goods             1086
Canned                   1084
Health and Hygiene        858
Meat                      736
Soft Drinks               726
Breads                    416
Hard Drinks               362
Others                    280
Starchy Foods             269
Breakfast                 186
Seafood                    89
Name: count, dtype: int64

In [ ]:
df.replace({'Item_Type':{'Fruits and Vegetables':0,
                         'Snack Foods':0,'Household':1,'Frozen Foods':0,'Dairy':0,
                         'Baking Goods':0,'Canned':0,'Health and Hygiene':1,'Meat':0,'Soft Drinks':0
                         ,'Breads':0,'Hard Drinks':0,'Others':2,'Starchy Foods':0,
                         'Breakfast':0,'Seafood':0}},inplace=True)

In [ ]:
df[['Item_Type']].value_counts()

Item_Type
0            11518
1             2406
2              280
Name: count, dtype: int64

In [ ]:
df[['Outlet_Identifier']].value_counts()

Outlet_Identifier
OUT027               1559
OUT013               1553
OUT046               1550
OUT049               1550
OUT035               1550
OUT045               1548
OUT018               1546
OUT017               1543
OUT010                925
OUT019                880
Name: count, dtype: int64

In [ ]:
df.replace({'Outlet_Identifier':{'OUT027':0,'OUT013':1,
                                 'OUT049':2,'OUT046':3,'OUT035':4,
                                 'OUT045':5,'OUT018':6,
                                 'OUT017':7,'OUT010':8,'OUT019':9,}},inplace=True)

In [ ]:
df[['Outlet_Identifier']].value_counts()

Outlet_Identifier
0                    1559
1                    1553
2                    1550
3                    1550
4                    1550
5                    1548
6                    1546
7                    1543
8                     925
9                     880
Name: count, dtype: int64

In [ ]:
df[['Outlet_Size']].value_counts()

Outlet_Size
Medium         7122
Small          5529
High           1553
Name: count, dtype: int64

In [ ]:
df.replace({'Outlet_Size':{'Small':0,'Medium':1,'High':2}},inplace=True)

In [ ]:
df[['Outlet_Size']].value_counts()

Outlet_Size
1              7122
0              5529
2              1553
Name: count, dtype: int64

In [ ]:
df[['Outlet_Location_Type']].value_counts()

Outlet_Location_Type
Tier 3                  5583
Tier 2                  4641
Tier 1                  3980
Name: count, dtype: int64

In [ ]:
df.replace({'Outlet_Location_Type':{'Tier 1':0,'Tier 2':1,'Tier 3':2}},inplace=True)

In [ ]:
df[['Outlet_Location_Type']].value_counts()

Outlet_Location_Type
2                       5583
1                       4641
0                       3980
Name: count, dtype: int64

In [ ]:


df['Outlet_Type'].value_counts()

Outlet_Type
Supermarket Type1    9294
Grocery Store        1805
Supermarket Type3    1559
Supermarket Type2    1546
Name: count, dtype: int64

In [ ]:
df.replace({'Outlet_Type':{'Supermarket Type1':1,'Grocery Store':0,'Supermarket Type2':2,'Supermarket Type3':3}},inplace=True)

In [ ]:
df['Outlet_Type'].value_counts()

Outlet_Type
1    9294
0    1805
3    1559
2    1546
Name: count, dtype: int64

In [ ]:
df.head()

Item_Identifier  Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  \
0           FDT36         12.3                 0         0.111448          0   
1           FDT36         12.3                 0         0.111904          0   
2           FDT36         12.3                 0         0.111728          0   
3           FDT36         12.3                 0         0.000000          0   
4           FDP12          9.8                 1         0.045523          0   

   Item_MRP  Outlet_Identifier  Outlet_Establishment_Year  Outlet_Size  \
0   33.4874                  2                       1999            1   
1   33.9874                  7                       2007            1   
2   33.9874                  6                       2009            1   
3   34.3874                  9                       1985            0   
4   35.0874                  7                       2007            1   

   Outlet_Location_Type  Outlet_Type  Item_Outlet_Sales  
0                     0            1         436.608721  
1                     1            1         443.127721  
2                     2            2         564.598400  
3                     0            0        1719.370000  
4                     1            1         352.874000

In [ ]:
df.shape

(14204, 12)

## **Define Target Variable (y) and Feature Variables (X)**

In [ ]:
y=df['Item_Outlet_Sales']
y.shape

(14204,)

In [ ]:
y

0         436.608721
1         443.127721
2         564.598400
3        1719.370000
4         352.874000
            ...     
14199    4984.178800
14200    2885.577200
14201    2885.577200
14202    3803.676434
14203    3644.354765
Name: Item_Outlet_Sales, Length: 14204, dtype: float64

In [ ]:
X=df.drop(['Item_Identifier','Item_Outlet_Sales'],axis=1)
X.shape

(14204, 10)

In [ ]:
X

Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  Item_MRP  \
0        12.300000                 0         0.111448          0   33.4874   
1        12.300000                 0         0.111904          0   33.9874   
2        12.300000                 0         0.111728          0   33.9874   
3        12.300000                 0         0.000000          0   34.3874   
4         9.800000                 1         0.045523          0   35.0874   
...            ...               ...              ...        ...       ...   
14199    12.800000                 0         0.069606          0  261.9252   
14200    12.800000                 0         0.070013          0  262.8252   
14201    12.800000                 0         0.069561          0  263.0252   
14202    13.659758                 0         0.069282          0  263.5252   
14203    12.800000                 0         0.069727          0  263.6252   

       Outlet_Identifier  Outlet_Establishment_Year  Outlet_Size  \
0                      2                       1999            1   
1                      7                       2007            1   
2                      6                       2009            1   
3                      9                       1985            0   
4                      7                       2007            1   
...                  ...                        ...          ...   
14199                  4                       2004            0   
14200                  7                       2007            1   
14201                  1                       1987            2   
14202                  0                       1985            1   
14203                  2                       1999            1   

       Outlet_Location_Type  Outlet_Type  
0                         0            1  
1                         1            1  
2                         2            2  
3                         0            0  
4                         1            1  
...                     ...          ...  
14199                     1            1  
14200                     1            1  
14201                     2            1  
14202                     2            3  
14203                     0            1  

[14204 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_std=df[['Item_Weight','Item_Visibility','Item_MRP','Outlet_Establishment_Year']]
X_std=sc.fit_transform(X_std)

In [ ]:
X_std

array([[-0.11541705,  0.88413635, -1.73178716,  0.13968068],
       [-0.11541705,  0.89300616, -1.72373366,  1.09531886],
       [-0.11541705,  0.88958331, -1.72373366,  1.3342284 ],
       ...,
       [ 0.00220132,  0.07011952,  1.96538148, -1.29377659],
       [ 0.20444792,  0.06469366,  1.97343499, -1.53268614],
       [ 0.00220132,  0.07334891,  1.97504569,  0.13968068]])

In [ ]:
X[['Item_Weight','Item_Visibility','Item_MRP','Outlet_Establishment_Year']]=pd.DataFrame(X_std,columns=[['Item_Weight','Item_Visibility','Item_MRP','Outlet_Establishment_Year']])

In [ ]:
X

Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  Item_MRP  \
0        -0.115417                 0         0.884136          0 -1.731787   
1        -0.115417                 0         0.893006          0 -1.723734   
2        -0.115417                 0         0.889583          0 -1.723734   
3        -0.115417                 0        -1.281712          0 -1.717291   
4        -0.703509                 1        -0.397031          0 -1.706016   
...            ...               ...              ...        ...       ...   
14199     0.002201                 0         0.070990          0  1.947664   
14200     0.002201                 0         0.078898          0  1.962160   
14201     0.002201                 0         0.070120          0  1.965381   
14202     0.204448                 0         0.064694          0  1.973435   
14203     0.002201                 0         0.073349          0  1.975046   

       Outlet_Identifier  Outlet_Establishment_Year  Outlet_Size  \
0                      2                   0.139681            1   
1                      7                   1.095319            1   
2                      6                   1.334228            1   
3                      9                  -1.532686            0   
4                      7                   1.095319            1   
...                  ...                        ...          ...   
14199                  4                   0.736955            0   
14200                  7                   1.095319            1   
14201                  1                  -1.293777            2   
14202                  0                  -1.532686            1   
14203                  2                   0.139681            1   

       Outlet_Location_Type  Outlet_Type  
0                         0            1  
1                         1            1  
2                         2            2  
3                         0            0  
4                         1            1  
...                     ...          ...  
14199                     1            1  
14200                     1            1  
14201                     2            1  
14202                     2            3  
14203                     0            1  

[14204 rows x 10 columns]

## **Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.3,random_state=2529)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4261, 10), (9943, 10), (4261,), (9943,))

## **Modeling**

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(random_state=2529)
rfr.fit(X_train,y_train)

RandomForestRegressor(random_state=2529)

## **Model Evaluation**

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mean_squared_error(y_test,y_pred)


1683520.463939761

In [ ]:
r2_score(y_test,y_pred)

0.49481055808912955

In [ ]:
mean_absolute_error(y_test,y_pred)

826.46660715427

An MAE of 826.47 means that, on average, your model's predictions are off by about 826 units from the actual sales values. Considering the mean sales value is 2185.83, this error represents roughly 38% of the average sale.



## **Prediction**

In [ ]:

y_pred=rfr.predict(X_test)

In [ ]:
y_pred.shape

(9943,)

In [ ]:
y_pred

array([1704.66708354,  471.9245452 , 2008.17117135, ...,  242.5999617 ,
       2293.77032733, 1697.42365979])

## **Explaination**

The "Big Sales Prediction" project aims to forecast future sales using historical data to assist businesses in making strategic decisions. It involves collecting historical sales data along with relevant external factors like Item weight,fat content. The data is then cleaned, features are engineered, and normalization is performed.I have used Random forest algorithm and performance is evaluated using metrics like MAE or R2 score.



In [ ]:
!pip install scikit-learn==1.3.0
from sklearn.model_selection import GridSearchCV

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 72.0 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.2
    Uninstalling scikit-learn-1.3.2:
      Successfully uninstalled scikit-learn-1.3.2


In [ ]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10]
}

In [ ]:
grid_search = GridSearchCV(estimator=rfr, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=2529),
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200]},
             scoring='neg_mean_squared_error')

In [ ]:
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'max_depth': 10, 'min_samples_split': 10, 'n_estimators': 50}


In [ ]:
y_pred_tuned = best_model.predict(X_test)
mse_tuned = mean_squared_error(y_test, y_pred_tuned)
print("Tuned MSE:", mse_tuned)

Tuned MSE: 1586620.41992852
